# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: GitVersion
      id: gitversion
      uses: nmcc/actions/gitversion@v1
      with:
        path-to-gitversion: packages/GitVersion.CommandLine/tools/GitVersion.exe

    - name: unit tests
      run: .\hsdp-iam.tests.ps1
      shell: pwsh

    # setup nuget
    - name: Download latest NuGet (cross-platform)
      uses: olegtarasov/download-nuget@v1

    - name: build/package
      run: .\build.ps1 ${{ steps.gitversion.outputs.major }} ${{ steps.gitversion.outputs.minor }} ${{ steps.gitversion.outputs.patch }}
      shell: pwsh

    - name: Make Nuget package (Non-Windows)
      run: mono $NUGET_EXE pack src/hsdp-iam.nuspec -OutputDirectory target

    - name: push to nuget
      if: github.event_name != 'pull_request'
      run: mono $NUGET_EXE push target/hsdp-iam.${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}.nupkg ${{ secrets.NUGET_APIKEY }} -Source https://api.nuget.org/v3/index.json
